DROP TABLE IF EXISTS  `kami`;
CREATE TABLE `kami` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `card` text NOT NULL,
  `credit` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
